### ISSUE TITLE
Getting TypeError: t.toLowerCase is not a function after upgrading to v3.15.1

### ISSUE THREAD

**Issue by tom-byrom** [yairEO/tagify#573]
## Prerequisites

- [YES ] I am running the latest version
- [YES ] I checked the documentation and found no answer
- [YES ] I checked to make sure that this issue has not already been filed

Below is my code to show the suggestions - was working perfectly prior to upgrading

```
        // Create tagify
        var inputElm = document.getElementById('tagifyField')
        var tagify = new Tagify(inputElm, {
            // Needed to output clean values for storage, default is JSON
            originalInputValueFormat: valuesArr => valuesArr.map(item => item.value).join(','),
            editTags: false,
            whitelist:[],
            dropdown : {
                enabled: 0,
                fuzzySearch: false,
                accentedSearch: false,   // allow adding duplicate items if their case is different
            },
            }),
            
            controller;

        // On input get create whitelist and get suggestions
        tagify.on('input', suggestedTags)


        // This is the function to create a whitelist and retrieve suggestions from it
        function suggestedTags( e ){
            var value = e.detail.value;
            tagify.settings.whitelist.length = 0; // reset the whitelist

            // https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort
           
            controller && controller.abort();
            controller = new AbortController();


            // show loading animation and hide the suggestions dropdown
            tagify.loading(false).dropdown.hide.call(tagify)

            // Fetch your url with JSON data
            fetch('https://example.com/tags.api', {signal:controller.signal})
            .then(RES => RES.json())
            .then(function(whitelist){
                
                // Target the data in the JSON array
                tagList = whitelist.data

                // Create whitelist from JSON array
                tagify.settings.whitelist = tagList
                tagify.loading(false).dropdown.show.call(tagify, value); // render the suggestions dropdown
            }
            )
        }

```

### Explanation

I just upgraded from 3.14.1 > Latest and now it breaks it, the suggestions list no longer shows and keep getting this error?

- **What error message are you getting?**

![image](https://user-images.githubusercontent.com/34626292/87425698-040f3480-c5d6-11ea-8612-0e77ba0c2a17.png)

It's referencing this line in my tagify code

` tagify.loading(false).dropdown.show.call(tagify, value); `

**Comment by yairEO** [comment]
I've worked in the last hours to fix many different things, please try version `3.14.2` and let me know

Thanks & sorry for that error!

**Comment by yairEO** [comment]
in your tagify code:

    tagify.loading(false).dropdown.show.call(tagify, value)

is `value` of **type** *String* or a *Number*?

**Comment by tom-byrom** [comment]
Hi @yairEO updating to 3.15.2 has fixed the issue.

My value variable is set using  `var value = e.detail.value;` as per the example documentation.

So its getting the input value which is a string

**Comment by yairEO** [comment]
good to hear it has been resolved. Regardless, I'm constantly working on improvements and sometimes things get broken and I rely on the community to report any issue. hundreds of different scenarios might happen and I cannot possibly check them all or write tests because it would be an insane amount for me to write, as a hobby on my spare time :)

**Comment by tom-byrom** [comment]
Really appreciate the quick responses and getting fixes out so quick!

I think I've finally managed to fully integrate tagify now anyway! So will let you know if I ever spot any other irregularities.

Thanks
