### ISSUE TITLE
Vue 2.7 compilation error when building application

### ISSUE THREAD

**Issue by szafran98** [yairEO/tagify#1066]
Hey,

after upgrading Vue from 2.6.14 to 2.7.5 I'm having a problem with build as in the screenshot.

![image](https://user-images.githubusercontent.com/28840579/178685003-fb1d2f48-0458-4bff-b541-48af4d9336ae.png)

How can I make it working again? I didn't do any code changes except changing Vue version.

**Comment by yairEO** [comment]
Closing as OP is non-responsive and the issue is vague and also I don't know Vue

**Comment by hansy** [comment]
Hmm getting this error on @yaireo/tagify@4.13.3 with nuxt@2.15.6.

The error is:
```
 ERROR  in ./node_modules/@yaireo/tagify/dist/tagify.min.js                                                                                                                                                               friendly-errors 22:57:45

Module parse failed: Unexpected token (26:30620)                                                                                                                                                                          friendly-errors 22:57:45
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

Rolled back to @yaireo/tagify@4.9.5 and everything seems fine again.

**Comment by yairEO** [comment]
Can you please create a _Codesandbox_ basic example so I could examine?

**Comment by mrcgrtz** [comment]
I have the same issue in a Gulp/Browserify setup, starting with v4.13. All versions below v4.13 don‘t have that issue, so right now I‘m sticking with v4.12.

I‘ll try to provide a minimal example as soon as possible.

**Comment by yairEO** [comment]
@mrcgrtz - Gulp + Vue? Since when does Vue compiles with Gulp?

**Comment by mrcgrtz** [comment]
@yairEO Sorry, I should have been more specific: No, this is not happening in a Vue codebase.

But this _might_ be an issue with some dependency along the way, like Terser, Uglify etc. which both Vue and my setup share. I have a TypeScript module importing Tagify which gets transpiled using Browserify and Gulp.

With v4.13 I get a `[SyntaxError]: Unexpected token: punc (.) while parsing file: /some_project/node_modules/@yaireo/tagify/dist/tagify.min.js` while with v4.12 everything’s running smooth.

But as I said, I’ll create a minimal example as soon as I have some spare time.

**Comment by yairEO** [comment]
at which point do you get this error? it does not state any line... you can use the unminified version of Tagify and replace your `tagify.min.js` in `node_modules` with that, and then you'll see exactly which line is causing it

**Comment by breakerh** [comment]
@yairEO This is the same issue as I had. Babel isn't setup correct to use optional chaining. Which you added in 4.13 it seems?

**Comment by yairEO** [comment]
I don't remember when did I add optional-chaining but your babel setup must be very old if it does not support that, which means you should update it regardless of Tagify, which is only one symptom. I also advise you to install `Browserlist` and configure it in your `package.json` file

**Comment by mrcgrtz** [comment]
For the sake of completeness: I could pinpoint my issue with the `unexpected token` down to the [minifier](https://github.com/browserify/tinyify) which uses an outdated version of `terser` that could not handle the optional chaining added to v4.13’s `dist` files.

I already had the latest version of `@babel/preset-env` and a sensible `.browserslistrc` file, so I now use the latest [`terser`](https://terser.org) directly and everything’s smooth again.

So no issue with this package apparently, sorry for the false alarm.

Maybe this helps other people when searching for this issue.
